#!/usr/bin/env bash

export MY_CONFIG_HOME="$HOME/.config"
export MY_DATA_HOME="$HOME/.local/share"
export MY_BIN_HOME="$HOME/.local/bin"

# Source config files that are not to be public (API tokens etc.)
if [ -r "$MY_CONFIG_HOME/bash-like/not-public" ]; then
	# shellcheck source=/dev/null
	source "$MY_CONFIG_HOME/bash-like/not-public"
fi

if [ -f "$MY_CONFIG_HOME/bash-like//shell-aliases" ]; then
	# shellcheck source=/dev/null
	source "$MY_CONFIG_HOME/bash-like/shell-aliases"
fi

export HISTSIZE=256000
export SAVEHIST=256000

export CLICOLOR=1

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="--history=$HOME/.fzf-history"

export HOMEBREW_NO_ANALYTICS=1

# save computer specific themes to .not-public
background_theme=$(change-theme)
export BACKGROUND_THEME=$background_theme

# export BAT_THEME=base16-256
# export BAT_THEME=base16
export BAT_THEME=ansi
