#!/usr/bin/env bash

cdl() {
	cd "$@" || exit
	ls -al
}

wiki() {
	cd "$HOME/Dropbox/wiki" || exit
	if [[ $# -eq 1 ]]; then
		vim -c ':copen' -q <(rg --vimgrep -S $# "$HOME/Dropbox/wiki")
		return
	else
		vim -c ':VimwikiIndex'
		return
	fi
}

if [[ $OSTYPE == "linux-gnu" ]] && [[ "$(</proc/sys/kernel/osrelease)" == *Microsoft ]] && [ -t 1 ]; then
	alias open="wslview"
else
	case "$OSTYPE" in
	cygwin*)
		alias open="cmd /c start"
		;;
	linux*)
		alias open="xdg-open"
		;;
	darwin*) ;;

	esac
fi
