[[item]]
file = "~/.config/kitty/colors.conf"
template = "kitty"
rewrite = true

[[item]]
file = "~/.shell-colors"
template = "shell"
rewrite = true

[[item]]
file = "~/.tmux-colors.conf"
template = "tmux"
rewrite = true

# vim doesn't play nicely with flavours so let's not use it
# [[item]]
# file = "~/.vim-colors"
# template = "vim"
# rewrite = true
